# -*- coding: utf-8 -*-
"""
Created on Mon Dec 28 22:14:04 2015

@author: easypc
"""

def GroupedPoiEmails ():
    
    emails = {'BELDEN TIMOTHY N': ['tbelden@enron.com',
  'tim.belden@enron.com',
  'tim_belden@pgn.com',
  'tbelden@ect.enron.com'],
 'BOWEN JR RAYMOND M': ['jbrown@enron.com', 'james.brown@enron.com'],
 'CALGER CHRISTOPHER F': ['calger@enron.com',
  'chris.calger@enron.com',
  'christopher.calger@enron.com',
  'ccalger@enron.com'],
 'CAUSEY RICHARD A': ['rick.causey@enron.com',
  'richard.causey@enron.com',
  'rcausey@enron.com'],
 'COLWELL WESLEY': ['wes.colwell@enron.com'],
 'DELAINEY DAVID W': ['david.w.delainey@enron.com',
  'delainey.dave@enron.com',
  "'delainey@enron.com",
  'david.delainey@enron.com',
  "'david.delainey'@enron.com",
  'dave.delainey@enron.com',
  "delainey'.'david@enron.com"],
 'FASTOW ANDREW S': ['andrew.fastow@enron.com',
  'lfastow@pdq.net',
  'andrew.s.fastow@enron.com',
  'lfastow@pop.pdq.net',
  'andy.fastow@enron.com'],
 'HANNON KEVIN P': ['kevin_hannon@enron.com',
  "kevin'.'hannon@enron.com",
  'kevin_hannon@enron.net',
  'kevin.hannon@enron.com'],
 'HIRKO JOSEPH': ["joe'.'hirko@enron.com", 'joe.hirko@enron.com'],
 'KOPPER MICHAEL J': ['michael.kopper@enron.com'],
 'LAY KENNETH L': ['kenneth_lay@enron.net',
  'kenneth_lay@enron.com',
  'klay.enron@enron.com',
  'kenneth.lay@enron.com',
  'klay@enron.com',
  'layk@enron.com',
  'chairman.ken@enron.com'],
 'RICE KENNETH D': ["ken'.'rice@enron.com",
  'ken.rice@enron.com',
  'ken_rice@enron.com',
  'ken_rice@enron.net'],
 'RIEKER PAULA H': ['paula.rieker@enron.com', 'prieker@enron.com'],
 'SHELBY REX': ['rex.shelby@enron.com',
  'rex.shelby@enron.nt',
  'rex_shelby@enron.net'],
 'SKILLING JEFFREY K': ['jeffreyskilling@yahoo.com',
  'jeff_skilling@enron.com',
  'jskilling@enron.com',
  'effrey.skilling@enron.com',
  'skilling@enron.com',
  'jeffrey.k.skilling@enron.com',
  'jeff.skilling@enron.com'],
 'YEAGER F SCOTT': ['scott.yeager@enron.com',
  'syeager@fyi-net.com',
  'scott_yeager@enron.net',
  'syeager@flash.net']}
    return emails